services:
  rag:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - ./test_tenders:/app/test_tenders

    stdin_open: true
    tty: true